name: Publish Docker Image

on:
  push:
    branches: ["master"]

jobs:
  push_to_registry:
    runs-on: self-hosted
    name: Push Docker Image to Dockerhub
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/lm-server:latest

  # deploy:
  #   needs: push_to_registry
  #   runs-on: self-hosted

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Kubectl
  #       uses: azure/setup-kubectl@v1

  #     - name: Configure Kubernetes context
  #       uses: azure/k8s-set-context@v1
  #       with:
  #         kubeconfig: ${{ secrets.KUBECONFIG }}

  #     - name: Deploy to Kubernetes
  #       run: kubectl apply -f ./K8-configs/deployment.yaml
